### PR TITLE
SBEE-46: Out of Support Update

### PR DESCRIPTION
**Pull request by spjmurray**

### CODE REVIEW

**Comment by spjmurray** [comment]
This is essentially abandonware, and now has a technical limit where it can be used.  May as well make this live.

**Review by RichardSmedley — APPROVED** [review]
:+1:

**Comment by RichardSmedley** [comment]
Looks like Eric and Amarantha are still down as approvers.

**Review by maria-robobug — APPROVED** [review]

**Comment by RichardSmedley** [comment]
I can't see who has permissions to approve here @spjmurray - guessing you and @roshanisanghavi - but I don't think anyone who is still in docs.

This needs addressing, and is on our agenda.

**Review by codingminions — APPROVED** [review]
I don't know if I have the permission to approve, but this looks good as per other members, giving it the last "required" approval.

**Comment by codingminions** [comment]
I now have the power!

**Pull request merged**
